// 10 examples of data for seeding, generated by ai cus im sleepy

export const usersData = [
    { name: 'Ana Souza',       email: 'ana@email.com'      },
    { name: 'Bruno Lima',      email: 'bruno@email.com'    },
    { name: 'Carla Mendes',    email: 'carla@email.com'    },
    { name: 'Diego Ferreira',  email: 'diego@email.com'    },
    { name: 'Eduarda Costa',   email: 'eduarda@email.com'  },
    { name: 'Felipe Rocha',    email: 'felipe@email.com'   },
    { name: 'Gabriela Nunes',  email: 'gabriela@email.com' },
    { name: 'Henrique Pinto',  email: 'henrique@email.com' },
    { name: 'Isabela Martins', email: 'isabela@email.com'  },
    { name: 'João Marcos',     email: 'joao@email.com'     },
];

export const storesData = [
    { name: 'Pizza Express',       category: 'pizza',     address: 'Av. Brasil, 123'       },
    { name: 'Burger Palace',       category: 'burger',    address: 'Rua das Flores, 456'   },
    { name: 'Sushi Osaka',         category: 'japanese',  address: 'Alameda Santos, 789'   },
    { name: 'Churrascaria Gaúcha', category: 'brazilian', address: 'Av. Paulista, 1000'    },
    { name: 'China Garden',        category: 'chinese',   address: 'Rua Augusta, 321'      },
    { name: 'Padaria Bom Dia',     category: 'bakery',    address: 'Rua Consolação, 55'    },
    { name: 'Salad & Co',          category: 'healthy',   address: 'Av. Faria Lima, 888'   },
    { name: 'Doceria da Vila',     category: 'desserts',  address: 'Rua Oscar Freire, 200' },
    { name: 'Bar do Zé',           category: 'drinks',    address: 'Rua Bela Cintra, 77'   },
    { name: 'Mercadinho Central',  category: 'grocery',   address: 'Av. Rebouças, 450'     },
];

export function buildProductsData(stores) {
    return [
        { name: 'Pizza Margherita',     price: 45.90, storeId: stores[0]._id },
        { name: 'Pizza Calabresa',      price: 49.90, storeId: stores[0]._id },
        { name: 'X-Burguer Clássico',   price: 32.00, storeId: stores[1]._id },
        { name: 'Combo Temaki + Missô', price: 58.00, storeId: stores[2]._id },
        { name: 'Picanha na Brasa',     price: 89.90, storeId: stores[3]._id },
        { name: 'Yakisoba de Frango',   price: 38.00, storeId: stores[2]._id },
        { name: 'Pão de Queijo (6 un)', price: 14.00, storeId: stores[5]._id },
        { name: 'Bowl Proteico',        price: 42.50, storeId: stores[6]._id },
        { name: 'Brownie com Sorvete',  price: 22.00, storeId: stores[7]._id },
        { name: 'Limonada Suíça',       price: 12.00, storeId: stores[8]._id },
    ];
}

export function buildOrdersData(users, stores, products) {
    return [
        { userId: users[0]._id, storeId: stores[0]._id, products: [products[0]._id],                  total: 45.90, status: 'delivered'  },
        { userId: users[1]._id, storeId: stores[1]._id, products: [products[2]._id],                  total: 32.00, status: 'delivered'  },
        { userId: users[2]._id, storeId: stores[2]._id, products: [products[3]._id, products[5]._id], total: 96.00, status: 'approved'   },
        { userId: users[3]._id, storeId: stores[3]._id, products: [products[4]._id],                  total: 89.90, status: 'delivering' },
        { userId: users[4]._id, storeId: stores[0]._id, products: [products[0]._id, products[1]._id], total: 95.80, status: 'pending'    },
        { userId: users[5]._id, storeId: stores[5]._id, products: [products[6]._id],                  total: 14.00, status: 'delivered'  },
        { userId: users[6]._id, storeId: stores[6]._id, products: [products[7]._id],                  total: 42.50, status: 'approved'   },
        { userId: users[7]._id, storeId: stores[7]._id, products: [products[8]._id],                  total: 22.00, status: 'cancelled'  },
        { userId: users[8]._id, storeId: stores[8]._id, products: [products[9]._id],                  total: 12.00, status: 'pending'    },
        { userId: users[9]._id, storeId: stores[2]._id, products: [products[3]._id],                  total: 58.00, status: 'delivering' },
    ];
}